name: deploy GAE

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0  # 수정된 부분: 명시적인 버전 사용
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true  # 수정된 부분: 기본 자격증명으로 내보냄

      - name: Deploy to Google App Engine
        run: |
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud -q app deploy app.yaml --promote
          # gcloud -q app deploy cron.yaml  # 필요한 경우 주석 해제
